"""init

Revision ID: 6c5f431ed45d
Revises: 
Create Date: 2022-06-27 15:38:17.235345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c5f431ed45d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('hash', sa.String(length=512), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('duplicate_counter', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_image_hash'), 'image', ['hash'], unique=True)
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.create_table('thumbnail',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('image_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnail_id'), 'thumbnail', ['id'], unique=False)
    op.create_index(op.f('ix_thumbnail_image_id'), 'thumbnail', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnail_image_id'), table_name='thumbnail')
    op.drop_index(op.f('ix_thumbnail_id'), table_name='thumbnail')
    op.drop_table('thumbnail')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_index(op.f('ix_image_hash'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
